#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# ForgeOS docker-compose setup.
#
# Generates a .env file in this directory with:
#   - DB_PASSWORD       random 32-byte hex string
#   - ANTHROPIC_API_KEY (empty — user must fill in)
#   - OPENAI_API_KEY    (empty — optional)
#
# Idempotent: does nothing if .env already exists (won't clobber your keys).
# ----------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")"
ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo "$ENV_FILE already exists — refusing to overwrite."
  echo "Delete it manually if you want to regenerate."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl not found — please install it."
  exit 1
fi

DB_PASSWORD=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# ForgeOS docker-compose environment
# Generated by docker-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE — it contains secrets.

# Random Postgres password (required)
DB_PASSWORD=${DB_PASSWORD}

# Anthropic API key (required for real LLM calls; leave empty for simulated mode)
ANTHROPIC_API_KEY=

# OpenAI API key (optional)
OPENAI_API_KEY=

# Dashboard auth password (set to whatever you want; default is "forgeos")
FORGEOS_DEV_PASSWORD=forgeos
EOF

chmod 600 "$ENV_FILE"

echo "Created $ENV_FILE with a random DB_PASSWORD."
echo ""
echo "Next steps:"
echo "  1. Edit $ENV_FILE and set ANTHROPIC_API_KEY"
echo "  2. Run: docker compose --env-file $ENV_FILE up --build"
echo ""
