"""
Conversation managers — pluggable context window strategies.

Strategies for keeping conversation history within token limits:
- SlidingWindowManager: keep system prompt + last N messages
- SummarizingManager: summarize older messages into a compact block
- NullManager: no management (current behavior)
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
import logging

logger = logging.getLogger(__name__)


@runtime_checkable
class ConversationManager(Protocol):
    """Protocol for conversation management strategies."""

    def reduce(self, messages: list[dict], max_messages: int | None = None) -> list[dict]:
        """Reduce messages to fit within limits. Returns a new list."""
        ...


class NullManager:
    """No management — returns messages unchanged."""

    def reduce(self, messages: list[dict], max_messages: int | None = None) -> list[dict]:
        return messages


class SlidingWindowManager:
    """Keep system prompt + last N messages.

    Preserves the system prompt (first message if role=system) and
    keeps only the most recent `window_size` messages after it.
    """

    def __init__(self, window_size: int = 20):
        self.window_size = window_size

    def reduce(self, messages: list[dict], max_messages: int | None = None) -> list[dict]:
        if not messages:
            return messages

        limit = max_messages or self.window_size

        # Separate system prompt from conversation
        system_msgs = []
        conversation = []
        for msg in messages:
            if msg.get("role") == "system":
                system_msgs.append(msg)
            else:
                conversation.append(msg)

        # If within limit, return unchanged
        if len(conversation) <= limit:
            return system_msgs + conversation

        # Keep last N messages
        trimmed = conversation[-limit:]
        logger.debug("SlidingWindow: trimmed %d → %d messages", len(conversation), len(trimmed))
        return system_msgs + trimmed


class SummarizingManager:
    """Summarize older messages to save tokens.

    When conversation exceeds `summary_threshold` messages, older messages
    are replaced with a summary block. The summary is generated by calling
    a provided summarize function, or falls back to a simple truncation.
    """

    def __init__(self, summary_threshold: int = 30, keep_recent: int = 10,
                 summarize_fn=None):
        self.summary_threshold = summary_threshold
        self.keep_recent = keep_recent
        self._summarize_fn = summarize_fn

    def reduce(self, messages: list[dict], max_messages: int | None = None) -> list[dict]:
        if not messages:
            return messages

        threshold = max_messages or self.summary_threshold

        # Separate system prompt
        system_msgs = []
        conversation = []
        for msg in messages:
            if msg.get("role") == "system":
                system_msgs.append(msg)
            else:
                conversation.append(msg)

        # If within threshold, return unchanged
        if len(conversation) <= threshold:
            return system_msgs + conversation

        # Split into old (to summarize) and recent (to keep)
        old_messages = conversation[:-self.keep_recent]
        recent_messages = conversation[-self.keep_recent:]

        # Generate summary
        summary_text = self._generate_summary(old_messages)

        # Build result: system + summary block + recent
        summary_msg = {
            "role": "system",
            "content": f"[Conversation summary — {len(old_messages)} earlier messages]\n{summary_text}",
        }

        result = system_msgs + [summary_msg] + recent_messages
        logger.debug("Summarizing: %d messages → summary + %d recent",
                    len(conversation), len(recent_messages))
        return result

    def _generate_summary(self, messages: list[dict]) -> str:
        """Generate a summary of messages."""
        if self._summarize_fn:
            try:
                return self._summarize_fn(messages)
            except Exception as e:
                logger.error("Summary function failed: %s", e)

        # Fallback: extract key points from assistant messages
        points = []
        for msg in messages:
            role = msg.get("role", "")
            content = msg.get("content", "")
            if role == "assistant" and content:
                first_line = content.split("\n")[0][:100]
                if first_line:
                    points.append(first_line)
            elif role == "user" and content:
                points.append(f"User asked: {content[:80]}")

        if not points:
            return "Earlier conversation context (details summarized)."

        # Keep at most 10 key points
        return "\n".join(f"- {p}" for p in points[:10])
